category_log: station-12306
frequency_time: 5
#是否需要增加日期
date_need_add: false
#是否使用代理
if_use_proxy: false
#代理使用
proxy_frequency_time: 10
# nice 最大值设置
catch_num: 20
download_workers_size: 16
extractor_workers_size: 10
proxy_checker_size: 5
links_queue_min_size: 12288
batch_add_links_size: 4096
check_url: "https://www.ly.com/uniontrain/trainapi/TrainPCCommon/SearchTrainRemainderTickets?callback=jQuery1830414364584783371_1499395892747&para={%22To%22:%22%E5%B9%BF%E5%B7%9E%22,%22From%22:%22%E5%93%88%E5%B0%94%E6%BB%A8%22,%22TrainDate%22:%222017-07-25%22,%22PassType%22:%22%22,%22TrainClass%22:%22%22,%22FromTimeSlot%22:%22%22,%22ToTimeSlot%22:%22%22,%22FromStation%22:%22%22,%22ToStation%22:%22%22,%22SortBy%22:%22fromTime%22,%22callback%22:%22%22,%22tag%22:%22%22,%22memberId%22:%220%22,%22headct%22:%220%22,%22platId%22:1,%22headver%22:%221.0.0%22,%22headtime%22:1499395893673}"
download_headers:
    - "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    - "Accept-Encoding:gzip, deflate, sdch"
    - "Accept-Language:zh-CN,zh;q=0.8,en;q=0.6"
    - "Cache-Control:max-age=0"
    - "Connection:keep-alive"
    - "Host: www.ly.com"
    - "Upgrade-Insecure-Requests:1"
check_url:
    - "Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8"
    - "Accept-Encoding:gzip, deflate, sdch"
    - "Accept-Language:zh-CN,zh;q=0.8,en;q=0.6"
    - "Cache-Control:max-age=0"
    - "Connection:keep-alive"
    - "Host: www.ly.com"
    - "Upgrade-Insecure-Requests:1"
    - "User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"